[api]
enabled = true
port = 54321
schemas = ["public", "graphql_public"]
extra_search_path = ["public"]

[db]
major_version = 17

[db.migrations]
directory = "supabase/migrations"

[functions]
enabled = true

[edge_runtime]
enabled = true
policy = "per_worker"

[functions.paystack-webhook]
verify_jwt = false

[functions.release-escrow]
verify_jwt = true

[experimental]
orioledb_version = "1.3.5"
